# 1. Create a 3x3x3 array with random values 

In [1]:
from numpy import  array as ar
import numpy as np
import random
z=np.random.rand(3,3,3) 
print(z)



[[[0.21961698 0.38315132 0.9232932 ]
  [0.56893676 0.26437041 0.52776674]
  [0.25237743 0.14805223 0.16863334]]

 [[0.72232133 0.77804948 0.88459999]
  [0.85015608 0.97126779 0.22349589]
  [0.41989713 0.76093481 0.05348865]]

 [[0.5902759  0.41473058 0.97217689]
  [0.16000516 0.0838167  0.53038508]
  [0.23408253 0.5583855  0.18800439]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
ans2=np.zeros((5,5))
for i in range(1,5):
    ans2[i,i-1]=i
ans2

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
ans3=np.zeros((8,8))
ans3[0::2,1::2]=1
ans3[1::2,0::2]=1
ans3

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [4]:
import math
ans4=np.random.rand(5,5)
t= np.linalg.det(ans4)
d=math.sqrt(math.pow(t,2))
ans4=ans4/d
print(ans4)

[[14.12163623  0.42182796 30.00397352 15.23477585 10.93239224]
 [20.47488073 22.3954664   5.73803262 24.34149248  5.44012118]
 [ 5.84181968 20.92909694 21.68401312 23.86428268  3.49510644]
 [17.18157522 22.91322601 10.31156931  7.18703036 13.46500462]
 [15.78071637  2.28061062  1.13420333 16.47309012  4.83473409]]


# 5.  How to find common values between two arrays?

In [5]:
a1=ar([[2,3,4],
       [5,6,7],
      [8,9,10]])
a2=ar([[2,35,4],
       [10,6,7],
      [83,91,10]])
inter=np.intersect1d(a1, a2)
print("The common elements are:",inter)



The common elements are: [ 2  4  6  7 10]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [7]:
a1=ar([[2,3,4],
       [5,6,7],
      [8,9,10]])
a2=ar([[2,3,4],
       [50,6,7],
      [8,9,10]])
z=a1==a2
z

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
z=np.random.rand(10)
m=max(z)
print(m)
for i in range(0,10):
    if(z[i]==m):
        z[i]=0
z

0.736980082400804


array([0.        , 0.49538387, 0.10238827, 0.39149009, 0.6662653 ,
       0.41220595, 0.45442471, 0.49665765, 0.61036831, 0.26340846])

# 9. How to print all the values of an array?

In [9]:
a1=ar([[2,3,4],
       [5,6,7],
      [8,9,10]])
r=a1.shape[0]
c=a1.shape[1]
for i in range(0,r):
    for j in range(0,c):
        print("value at",i,j,"is",a1[i][j])


value at 0 0 is 2
value at 0 1 is 3
value at 0 2 is 4
value at 1 0 is 5
value at 1 1 is 6
value at 1 2 is 7
value at 2 0 is 8
value at 2 1 is 9
value at 2 2 is 10


# 10.Subtract the mean of each row of a matrix

In [10]:
a1=ar([[2,3,4],
       [5,6,7],
      [8,9,10]])
r=a1.shape[0]
c=a1.shape[1]
m=a1.mean(axis=1)
print(m)
a1=a1-m
a1

[3. 6. 9.]


array([[-1., -3., -5.],
       [ 2.,  0., -2.],
       [ 5.,  3.,  1.]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

# 12.How to get the diagonal of a dot product?

In [11]:
a1=ar([[2,3,4],
       [5,6,7],
      [8,9,10]])
a2=ar([[2,3,4],
       [50,6,7],
      [8,9,10]])
dot=np.dot(a1,a2)
print(dot)
for i in range(0,3):
    print("the diagonal element is:",dot[i][i])
        

[[186  60  69]
 [366 114 132]
 [546 168 195]]
the diagonal element is: 186
the diagonal element is: 114
the diagonal element is: 195


# 13.How to find the most frequent value in an array?

In [12]:
a1=ar([2,25,2,2,2,2,2,2,2,3,5,6,7,4,3,4,2,4,5,3,3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
r=np.bincount(a1).argmax()
print("the most repeated value is",r)


the most repeated value is 1


# 14.How to get the n largest values of an array

In [28]:
a10=ar([9,8,7,6,5,3,4,256,100,76,898,864,1,2,34,46000])
n=4
a11=np.argsort(a10)
print (a10[a11])


[    1     2     3     4     5     6     7     8     9    34    76   100
   256   864   898 46000]


# 15.How to create a record array from a regular array?